### ISSUE TITLE
Starting game on Win10x64 crashes the game (MCI/MediaPlayer problem)

### ISSUE THREAD

**Issue by phomm** [devapromix-roguelikes/disciplesrl#1]
Error says: A problem occurred in initializing MCI.

If the game could handle error in MCI on startup then it could launch without music, but not throwing errors.
Code should catch exception on MediaPlayer := TPhoenixMediaPlayer.Create; store whether it succeeded or not and skip calling SetSceneMusic (or just Exit inside if music init failed), I've tried to comment those steps and it works fine.

**Comment by phomm** [comment]
Maybe there is better option for music, if Phoenix is not so well with newer windows?

**Comment by phomm** [comment]
added pr #3 to fix this

**Comment by devapromix** [comment]
Thank! It was the fastest way to add music and sounds to the game. Maybe there is something else?
