### ISSUE TITLE
Can't start new game (need to restart app)  in particular case

### ISSUE THREAD

**Issue by phomm** [devapromix-roguelikes/disciplesrl#2]
deleted, see below about bug

**Comment by phomm** [comment]
Bug is not about playing game, bug only a menu bug. The way to reproduce bug: start new game, press play, chose any game(or nothing, the dark tower is default), continue, then cancel on "chose faction" screen, and after that continue (in choose game screen) is not working

**Comment by devapromix** [comment]
Thanks for the test! Suddenly! What could be the mistake?
